export const exercises = [
  // ── CHEST ──────────────────────────────────────────────────────────────
  { id: '1', name: 'Barbell Bench Press', muscle: 'Chest', equipment: 'Barbell', youtube: 'rT7DgCr-3pg', bodyweight: false },
  { id: '31', name: 'Incline Barbell Bench Press', muscle: 'Chest', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '32', name: 'Decline Barbell Bench Press', muscle: 'Chest', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '33', name: 'Dumbbell Bench Press', muscle: 'Chest', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '34', name: 'Incline Dumbbell Press', muscle: 'Chest', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '35', name: 'Decline Dumbbell Press', muscle: 'Chest', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '36', name: 'Smith Machine Bench Press', muscle: 'Chest', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '37', name: 'Smith Machine Incline Press', muscle: 'Chest', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '38', name: 'Machine Chest Press', muscle: 'Chest', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '39', name: 'Machine Incline Press', muscle: 'Chest', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '40', name: 'Cable Crossover', muscle: 'Chest', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '41', name: 'Low Cable Fly', muscle: 'Chest', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '42', name: 'High Cable Fly', muscle: 'Chest', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '2', name: 'Push Ups', muscle: 'Chest', equipment: 'Bodyweight', youtube: 'IODxDxX7oi4', bodyweight: true },
  { id: '3', name: 'Diamond Push Ups', muscle: 'Chest', equipment: 'Bodyweight', youtube: 'J0DnG1_S92I', bodyweight: true },
  { id: '4', name: 'Incline Push Ups', muscle: 'Chest', equipment: 'Bodyweight', youtube: 'cfns5VDVVvk', bodyweight: true },
  { id: '43', name: 'Wide Push Ups', muscle: 'Chest', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '44', name: 'Decline Push Ups', muscle: 'Chest', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '45', name: 'Dips (Chest)', muscle: 'Chest', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '46', name: 'Pec Deck', muscle: 'Chest', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '47', name: 'Dumbbell Fly', muscle: 'Chest', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '48', name: 'Incline Dumbbell Fly', muscle: 'Chest', equipment: 'Dumbbell', youtube: '', bodyweight: false },

  // ── BACK ───────────────────────────────────────────────────────────────
  { id: '10', name: 'Deadlift', muscle: 'Back', equipment: 'Barbell', youtube: 'XxWcirHIwVo', bodyweight: false },
  { id: '49', name: 'Sumo Deadlift', muscle: 'Back', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '13', name: 'Barbell Row', muscle: 'Back', equipment: 'Barbell', youtube: 'FWJR5Ve8bnQ', bodyweight: false },
  { id: '50', name: 'Pendlay Row', muscle: 'Back', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '51', name: 'Dumbbell Row', muscle: 'Back', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '52', name: 'Dumbbell Seal Row', muscle: 'Back', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '53', name: 'Smith Machine Row', muscle: 'Back', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '14', name: 'Lat Pulldown', muscle: 'Lats', equipment: 'Cable', youtube: 'CAwf7n6Luuc', bodyweight: false },
  { id: '54', name: 'Lat Pulldown (Close Grip)', muscle: 'Lats', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '55', name: 'Seated Cable Row (Wide)', muscle: 'Back', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '56', name: 'Seated Cable Row (Close)', muscle: 'Back', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '57', name: 'T-Bar Row', muscle: 'Back', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '58', name: 'Chest-Supported Row', muscle: 'Back', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '59', name: 'Machine Row (Plate Loaded)', muscle: 'Back', equipment: 'Machine (plate-loaded)', youtube: '', bodyweight: false },
  { id: '60', name: 'Machine Row (Stack)', muscle: 'Back', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '11', name: 'Pull Ups', muscle: 'Back', equipment: 'Bodyweight', youtube: 'eGo4IYlbE5g', bodyweight: true },
  { id: '61', name: 'Chin Ups', muscle: 'Back', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '62', name: 'Neutral Grip Pull Ups', muscle: 'Back', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '63', name: 'Straight Arm Pulldown', muscle: 'Lats', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '15', name: 'Face Pulls', muscle: 'Rear Delts', equipment: 'Cable', youtube: 'rep-qVOkqgk', bodyweight: false },
  { id: '64', name: 'Cable Pullover', muscle: 'Lats', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '65', name: 'Hyperextension', muscle: 'Back', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '12', name: 'Inverted Rows', muscle: 'Back', equipment: 'Bodyweight', youtube: 'XZV9IwluPjw', bodyweight: true },
  { id: '66', name: 'Dumbbell Pullover', muscle: 'Lats', equipment: 'Dumbbell', youtube: '', bodyweight: false },

  // ── SHOULDERS ──────────────────────────────────────────────────────────
  { id: '5', name: 'Overhead Press', muscle: 'Shoulders', equipment: 'Barbell', youtube: '_RlRDWO2jfg', bodyweight: false },
  { id: '67', name: 'Push Press', muscle: 'Shoulders', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '68', name: 'Dumbbell Shoulder Press (Seated)', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '69', name: 'Dumbbell Shoulder Press (Standing)', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '70', name: 'Smith Machine OHP', muscle: 'Shoulders', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '71', name: 'Machine Shoulder Press', muscle: 'Shoulders', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '7', name: 'Lateral Raises', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '3VcKaXpzqRo', bodyweight: false },
  { id: '72', name: 'Lateral Raise (Cable)', muscle: 'Shoulders', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '73', name: 'Front Raise (Dumbbell)', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '74', name: 'Front Raise (Cable)', muscle: 'Shoulders', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '75', name: 'Rear Delt Fly (Dumbbell)', muscle: 'Rear Delts', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '76', name: 'Rear Delt Fly (Machine)', muscle: 'Rear Delts', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '77', name: 'Arnold Press', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '78', name: 'Upright Row (Barbell)', muscle: 'Shoulders', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '79', name: 'Upright Row (Dumbbell)', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '80', name: 'Shrugs (Barbell)', muscle: 'Shoulders', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '81', name: 'Shrugs (Dumbbell)', muscle: 'Shoulders', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '82', name: 'Shrugs (Smith Machine)', muscle: 'Shoulders', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '6', name: 'Pike Push Ups', muscle: 'Shoulders', equipment: 'Bodyweight', youtube: 'sposDXWEB0A', bodyweight: true },
  { id: '83', name: 'Landmine Press', muscle: 'Shoulders', equipment: 'Barbell', youtube: '', bodyweight: false },

  // ── BICEPS ─────────────────────────────────────────────────────────────
  { id: '16', name: 'Barbell Curl', muscle: 'Biceps', equipment: 'Barbell', youtube: 'kwG2ipFRgfo', bodyweight: false },
  { id: '84', name: 'EZ Bar Curl', muscle: 'Biceps', equipment: 'EZ Bar', youtube: '', bodyweight: false },
  { id: '85', name: 'Dumbbell Curl (Standing)', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '86', name: 'Dumbbell Curl (Seated Incline)', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '87', name: 'Hammer Curl (Dumbbell)', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '88', name: 'Hammer Curl (Cable Rope)', muscle: 'Biceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '89', name: 'Preacher Curl (EZ Bar)', muscle: 'Biceps', equipment: 'EZ Bar', youtube: '', bodyweight: false },
  { id: '90', name: 'Preacher Curl (Dumbbell)', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '91', name: 'Cable Curl (Bar)', muscle: 'Biceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '92', name: 'Cable Curl (Single Arm)', muscle: 'Biceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '93', name: 'Concentration Curl', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '94', name: 'Spider Curl', muscle: 'Biceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '95', name: 'Machine Bicep Curl', muscle: 'Biceps', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },

  // ── TRICEPS ────────────────────────────────────────────────────────────
  { id: '96', name: 'Close Grip Bench Press', muscle: 'Triceps', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '97', name: 'Skull Crushers (EZ Bar)', muscle: 'Triceps', equipment: 'EZ Bar', youtube: '', bodyweight: false },
  { id: '98', name: 'Skull Crushers (Dumbbell)', muscle: 'Triceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '8', name: 'Tricep Pushdown', muscle: 'Triceps', equipment: 'Cable', youtube: '2-LAMcpzODU', bodyweight: false },
  { id: '99', name: 'Tricep Pushdown (V-Bar)', muscle: 'Triceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '100', name: 'Tricep Pushdown (Straight Bar)', muscle: 'Triceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '101', name: 'Overhead Tricep Extension (Cable)', muscle: 'Triceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '102', name: 'Overhead Tricep Extension (Dumbbell)', muscle: 'Triceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '9', name: 'Tricep Dips', muscle: 'Triceps', equipment: 'Bodyweight', youtube: '6kALZikXxLc', bodyweight: true },
  { id: '103', name: 'Kickbacks (Dumbbell)', muscle: 'Triceps', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '104', name: 'Kickbacks (Cable)', muscle: 'Triceps', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '105', name: 'Machine Tricep Extension', muscle: 'Triceps', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },

  // ── LEGS — QUADS ───────────────────────────────────────────────────────
  { id: '17', name: 'Squat', muscle: 'Quads', equipment: 'Barbell', youtube: 'bEv6CCg2BC8', bodyweight: false },
  { id: '106', name: 'Front Squat', muscle: 'Quads', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '107', name: 'Smith Machine Squat', muscle: 'Quads', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '24', name: 'Leg Press', muscle: 'Quads', equipment: 'Machine (plate-loaded)', youtube: 'IZxyjW7MPJQ', bodyweight: false },
  { id: '108', name: 'Leg Press (Horizontal)', muscle: 'Quads', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '109', name: 'Hack Squat', muscle: 'Quads', equipment: 'Machine (plate-loaded)', youtube: '', bodyweight: false },
  { id: '21', name: 'Bulgarian Split Squat', muscle: 'Quads', equipment: 'Bodyweight', youtube: '2C-uNgKwPLE', bodyweight: true },
  { id: '110', name: 'Goblet Squat', muscle: 'Quads', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '111', name: 'Leg Extension', muscle: 'Quads', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '112', name: 'Walking Lunges', muscle: 'Quads', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '113', name: 'Reverse Lunges', muscle: 'Quads', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '114', name: 'Sissy Squat', muscle: 'Quads', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '115', name: 'Wall Sit', muscle: 'Quads', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '18', name: 'Bodyweight Squats', muscle: 'Quads', equipment: 'Bodyweight', youtube: 'aclHkVaku9U', bodyweight: true },
  { id: '20', name: 'Lunges', muscle: 'Quads', equipment: 'Bodyweight', youtube: 'QOVaHwm-Q6U', bodyweight: true },
  { id: '116', name: 'Step Ups', muscle: 'Quads', equipment: 'Dumbbell', youtube: '', bodyweight: false },

  // ── LEGS — HAMSTRINGS & GLUTES ─────────────────────────────────────────
  { id: '22', name: 'Romanian Deadlift', muscle: 'Hamstrings', equipment: 'Barbell', youtube: '7j-2w4-P14I', bodyweight: false },
  { id: '117', name: 'Romanian Deadlift (Dumbbell)', muscle: 'Hamstrings', equipment: 'Dumbbell', youtube: '', bodyweight: false },
  { id: '118', name: 'Stiff Leg Deadlift', muscle: 'Hamstrings', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '119', name: 'Lying Leg Curl', muscle: 'Hamstrings', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '120', name: 'Seated Leg Curl', muscle: 'Hamstrings', equipment: 'Machine (pin/stack)', youtube: '', bodyweight: false },
  { id: '121', name: 'Nordic Hamstring Curl', muscle: 'Hamstrings', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '122', name: 'Hip Thrust (Barbell)', muscle: 'Glutes', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '123', name: 'Hip Thrust (Smith Machine)', muscle: 'Glutes', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '124', name: 'Glute Bridge (Barbell)', muscle: 'Glutes', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '23', name: 'Glute Bridge', muscle: 'Glutes', equipment: 'Bodyweight', youtube: 'OUgsJ8-Vi0E', bodyweight: true },
  { id: '125', name: 'Cable Pull-Through', muscle: 'Glutes', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '126', name: 'Good Mornings', muscle: 'Hamstrings', equipment: 'Barbell', youtube: '', bodyweight: false },
  { id: '127', name: 'Single Leg Romanian Deadlift', muscle: 'Hamstrings', equipment: 'Dumbbell', youtube: '', bodyweight: false },

  // ── LEGS — CALVES ──────────────────────────────────────────────────────
  { id: '128', name: 'Standing Calf Raise (Machine)', muscle: 'Calves', equipment: 'Machine (plate-loaded)', youtube: '', bodyweight: false },
  { id: '129', name: 'Standing Calf Raise (Smith Machine)', muscle: 'Calves', equipment: 'Smith Machine', youtube: '', bodyweight: false },
  { id: '130', name: 'Seated Calf Raise', muscle: 'Calves', equipment: 'Machine (plate-loaded)', youtube: '', bodyweight: false },
  { id: '131', name: 'Leg Press Calf Raise', muscle: 'Calves', equipment: 'Machine (plate-loaded)', youtube: '', bodyweight: false },
  { id: '25', name: 'Calf Raises', muscle: 'Calves', equipment: 'Bodyweight', youtube: 'gwLzBJYoWlI', bodyweight: true },

  // ── ABDOMINALS & CORE ─────────────────────────────────────────────────
  { id: '132', name: 'Crunches', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '133', name: 'Reverse Crunches', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '134', name: 'Hanging Leg Raise', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '135', name: 'Hanging Knee Raise', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '136', name: 'Cable Crunch', muscle: 'Core', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '137', name: 'Ab Wheel Rollout', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '26', name: 'Plank', muscle: 'Core', equipment: 'Bodyweight', youtube: 'ASdvN_XEl_c', bodyweight: true },
  { id: '138', name: 'Side Plank', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '139', name: 'Russian Twist', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '28', name: 'Bicycle Crunches', muscle: 'Core', equipment: 'Bodyweight', youtube: '9FGilxCbdz8', bodyweight: true },
  { id: '140', name: 'Decline Sit-Up', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '141', name: 'Woodchops (Cable)', muscle: 'Core', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '142', name: 'Dead Bug', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '27', name: 'Mountain Climbers', muscle: 'Core', equipment: 'Bodyweight', youtube: 'nmwgirgXLYM', bodyweight: true },
  { id: '143', name: 'Pallof Press', muscle: 'Core', equipment: 'Cable', youtube: '', bodyweight: false },
  { id: '144', name: 'Toe Touches', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '145', name: 'Dragon Flag', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '146', name: 'Leg Raise (Lying)', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '147', name: 'V-Ups', muscle: 'Core', equipment: 'Bodyweight', youtube: '', bodyweight: true },

  // ── CARDIO / CONDITIONING ─────────────────────────────────────────────
  { id: '29', name: 'Burpees', muscle: 'Full Body', equipment: 'Bodyweight', youtube: 'TU8QYVW0gDU', bodyweight: true },
  { id: '19', name: 'Jump Squats', muscle: 'Quads', equipment: 'Bodyweight', youtube: 'A-cFYWvaHr0', bodyweight: true },
  { id: '148', name: 'Box Jumps', muscle: 'Full Body', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '149', name: 'Jumping Lunges', muscle: 'Quads', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '30', name: 'High Knees', muscle: 'Cardio', equipment: 'Bodyweight', youtube: 'D0lLwTwjVbE', bodyweight: true },
  { id: '150', name: 'Battle Ropes', muscle: 'Full Body', equipment: 'Bodyweight', youtube: '', bodyweight: true },
  { id: '151', name: 'Kettlebell Swings', muscle: 'Full Body', equipment: 'Kettlebell', youtube: '', bodyweight: false },
  { id: '152', name: "Farmer's Walk", muscle: 'Full Body', equipment: 'Dumbbell', youtube: '', bodyweight: false },
];

export const LOWER_BODY_MUSCLES = ['Quads', 'Hamstrings', 'Glutes', 'Calves'];

export function isLowerBody(muscle) {
  return LOWER_BODY_MUSCLES.includes(muscle);
}
